{% set version = "0.19.8.1" %}

package:
  name: gettext
  version: {{ version }}

source:
  url: ftp://ftp.gnu.org/pub/gnu/gettext/gettext-{{ version }}.tar.xz
  sha256: 105556dbc5c3fbbc2aa0edb46d22d055748b6f5c7cd7a8d99f8e7eb84e938be4

build:
  number: 1
  skip: true  # [win]
  run_exports:
    # Seems pretty good: https://abi-laboratory.pro/tracker/timeline/gettext/
    - {{ pin_subpackage('gettext') }}

requirements:
  build:
    - {{ compiler('c') }}
    - libffi
    - libiconv  # [not linux and not win]

test:
  commands:
    - test -f ${PREFIX}/lib/libgettextlib${SHLIB_EXT}  # [not win]

about:
  home: https://www.gnu.org/software/gettext/
  license: GPL-2.0
  license_file: COPYING
  summary: Internationalization package

extra:
  recipe-maintainers:
    - scopatz
    - ocefpaf
