{% set name = "gettext" %}
{% set version = "0.19.8.1" %}
{% set sha256 = "105556dbc5c3fbbc2aa0edb46d22d055748b6f5c7cd7a8d99f8e7eb84e938be4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.xz
  url: ftp://ftp.gnu.org/pub/gnu/{{ name }}/{{ name }}-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - libffi
    - libiconv  # [not linux and not win]

test:
  commands:
    - test -f ${PREFIX}/lib/libgettextlib.so  # [linux]
    - test -f ${PREFIX}/lib/libintl.dylib  # [osx]

about:
  home: https://www.gnu.org/software/gettext/
  license: GPLv2
  license_file: COPYING
  summary: "Internationalization package."
  description: |
  doc_url: https://www.gnu.org/software/gettext/manual/index.html
  dev_url: http://cvs.savannah.gnu.org/viewvc/gettext/
  doc_source_url: http://cvs.savannah.gnu.org/viewvc/gettext/gettext/doc/

extra:
  recipe-maintainers:
    - scopatz
