# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "BYosKNNWII4U7qdLO5ZPQA2tQbkFq605R0y5memcpiuorqFYM17GRkta/qE4mGL/HtuXDFstLy6H/3wkxCUlNC/in+j/OPIia2ytmbPDxANSzfMZSbhM+3vmMhs37qLcVtBxV3WAzYRYN0uPrlDEByA3N6KjFTcHKSHi7V2zS60hOjNiAI36Iwx1wpRrxViImKDS+d4SmMirpOcpj0IojGbTh1QtLV9Xmr81q3vK8LmYxbReaComTjI1k3tULxEFWh4bflYJr2H9oQ6baHqT+Bt2L36mlmSO+LCJyoFtGmb1FdudRiEYd+uIhA78psmXJMar6kVaVBwdCGEeljIczcIkqULGi8CA8PV/rvfYk4EFjSCutx8DPf96acKJjfsh73APDDtUqj0kTmfbcmV1hgJIHurjxTEBjSFR2lNMRrST6pfkUq7zjsksfJy9Is+4PNtg9GshqKFAfEH8ca/dSzAfuPfVs/FexWVlnXY/K7msF0mJBVggL/HwwezIFZBkgBoujdwGPMyKih+tT43KaPGPUEGyIbxdwGkv7cjo1q1iXM5XSSlnV+mEouS7Hic+5lLY/MxPwIXo5daeH9kOfzxMej5X8FuIWZTYyV2AovKGA+vI+hlxnMCO+xgsNlpFnx1B/+BHWXrPNKpqF1o9ZeFAo3w70GkvMRZYYaGcL38="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build=1.20.0 jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
