travis:
  secure:
    BINSTAR_TOKEN: oEQ2OKkpjDPArrUwNunXriyzSrxC8Bdv1VwlLpyCH7Ohu5IUqKQ8RLnP8YkW6MnJ/jTCZj7ScQdqbqmtp8Gy8q0cIgO6TBZVzDRQFW3nWRVvvx1LtqezKx7YpBmjDhRk0/prKVmyKxMkC7Xd+pPrXtNQsle9/zfqYh5X/dFtjqejTvHy65ZG3n0T8fPpGPCyR/9gmOG6EvqBkF7iUYw17CjXtB3hYJsUlBvYSN8NNvTLUoVy8AEK2m0VpC6ZMofad4Q1G/q0c66KWJx9J/HHq28i2SHNBV84gAg/QRq/zsvp8wzWD//oGZXv953gjo+rIQY/3KywWKTf3icj28NAe/sWXifeHvZ1uJlSBOhpJ6KaCOizOMDSXiLvukX5uke1UBO5rtuhRVZfER7FVaGrLZIQw1P7bSrt3UDvIm7XjSPsG2EBtQtDY4HAQKsUSidbxkq2H2AxI3GeNDek7WGCbYKa+x12i30427Z1i5c4/pELT++pcBXoZomWSC4SfXwGIYja6f7Pkb8bIJIaNGyJNXAIIufI/aB7jKTaeyHV0PQ4Q0XaYYzsgqfmQAoGnwIQKXRo9KGuww72gzVklnWpCcQPfKuw6NJnKz118bUUGIM6gytHzjfTEe16TTzRdKOKzuzf+ufqceUttIExWhGdSw6gm0GhGMO0mRuUj5CPK7U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
